Verify download

diff --git a/.github/workflows/on-release.yml b/.github/workflows/on-release.yml
--- a/.github/workflows/on-release.yml
+++ b/.github/workflows/on-release.yml
@@ -39,38 +39,14 @@ jobs:
           tag="${{ github.ref_name }}"
 
           url=$(echo '${{ toJson(github.event.release) }}' | jq --raw-output --arg t "$tag" 'select(.tag_name==$t) | .assets[] | .browser_download_url')
-          curl $url --fail --output $file
-
-      - name: Attach to release
-        shell: pwsh
-        run: |
-          $release = "${{ github.ref_name }}"
-          $repo = "${{ github.repository }}"
-          $token = "${{ env.GITHUB_TOKEN }}"
-          $uploadName = "vscode-metaed.vsix"
-
-          $url = "https://api.github.com/repos/$repo/releases/$release/assets"
-
-          $gh_headers = @{
-              "Accept"        = "application/vnd.github+json"
-              "Authorization" = "Bearer $token"
-          }
-
-          $response = Invoke-RestMethod -Uri $url -Headers $gh_headers
-          echo $response
-
-          $assetId = $response.id
-
-          $url = "https://uploads.github.com/repos/$repo/releases/assets/$assetId"
-
-          $gh_headers["Content-Type"] = "application/octet"
-          Invoke-RestMethod -Uri "$($url)?name=$($uploadName)" `
-              -Headers $gh_headers
-              -OutFile $uploadName
+          curl -LO $url --fail
+          if [ -s $file ]; then
+            echo "File Downloaded!"
+          else
+            echo "Error downloading file. Verify url: $url"
+            exit 1
+          fi
 
       - name: Publish to the marketplace
         run: |
-          cksum vscode-metaed.vsix
-          ls -l vscode-metaed.vsix
-          cat vscode-metaed.vsix
           npx vsce publish --allow-star-activation --packagePath vscode-metaed.vsix
